name: Build and Push to GCR

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build image
        run: docker build . --file ./app.Dockerfile --tag ${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
        working-directory: .

      - name: Push image
        run: docker push ${{ vars.ARTIFACT_REGISTRY_LOCATION }}/${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
