name: Build and Push to GCR

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/code-image-generator:${{ github.event.release.tag_name }}
          context: .
          file: ./app.Dockerfile
          # Add caching for Docker builds (if applicable)
          # cache-from: type=registry,source=gcr.io/${{ secrets.GCP_PROJECT_ID }}/code-image-generator:${{ github.event.release.tag_name }}
          # cache-to: type=inline
