name: Build and Push to GCR

on:
  release:
    types: [created]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file ./app.Dockerfile --tag ${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
        working-directory: .

      - name: Push image
        run: docker push ${{ vars.ARTIFACT_REGISTRY_LOCATION }}/${{ vars.IMAGE_NAME }}:${{ github.event.release.tag_name }}
