name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements-dev.txt"
      - run: pip install -r ./requirements-dev.txt
      - run: pip install flake8

      - name: Set up environment
        run: |
          export SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(16))')

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Test with pytest
        run: |
          pytest
